### ISSUE TITLE
Development and Maintenance Policy

### ISSUE THREAD

**Issue by daskol** [oseledets/ttpy#11]
There is not description of how to make changes, pull request and merge changes. So I propose to maintain the project in accordance to _git flow_ approach. Namely,

- branch `master` is only for stable versions and releases;
- branch `develop` is main working branch;
- contributor should create new branch for certain feature and then merge with `develop` branch as feature was done;
- each release on `master` branch should correspond to package on PyPI;
- there should be maintainer who checks all pull requests;
- there should be section in _README_ file on the landing page that describes contributor policy.

I believe these few points make development and maintenance easier, flexible and stable. As a result it produces bigger impact to community.

**Comment by oseledets** [comment]
@daskol Very good proposal, I fully support. 
Will do this in a few days (and discuss with those having commit rights to the "master" branch).
What do you mean by "contributor policy"? i.e., the text above about master/develop branches?

**Comment by daskol** [comment]
@oseledets I mean all text above and such rules as
- style and quality description of pull request;
- new changes should be tested and shouldn't break anything;
- pull request for one fix or one feature(could be several commits);
- keeping code style of the project;
- maintainer should be apparently specified(because there are five contributors who cannot sent pull request);

**Comment by oseledets** [comment]
Let us start this stuff.
