### ISSUE TITLE
libgfortran.so.3: version GFROTRAN_1.4 not found

### ISSUE THREAD

**Issue by kharyuk** [oseledets/ttpy#18]
This error occurs in the latest anaconda builds. How I have repaired it on my computer:

**1) Updated numpy and scipy**
_conda update numpy
conda update scipy_

**2) Installed accelerate package**
_conda install accelerate_

3) **According to link:**
http://stackoverflow.com/questions/36041964/messed-up-numpy-installation-gfortran-1-4-not-found-bug , **removed libgfortran and installed libgcc:**
_conda remove libgfortran
conda install libgcc --force_

**Comment by daskol** [comment]
Stale issue.
