### ISSUE TITLE
Definition of nn variable in the (z)tt_ksl.f90 subroutines

### ISSUE THREAD

**Issue by rborrelli** [oseledets/ttpy#25]
This conde sequence:

    lwork = rmax*maxval(n(1:d))*rmax
    nn = maxval(ra(1:d+1))*rmax*rmax
    allocate(curcr(lwork))
    nn = maxval(ra(1:d+1))*rmax*max(maxval(n(1:d)),maxval(m(1:d)))*rmax

appears both in the tt_ksl and ztt_ksl subroutines. The first definition of nn is not used, can it be removed?

**Comment by oseledets** [comment]
I think it is now fixed (with many other undefined variables stuff) in the develop branch of ttpy.
