### ISSUE TITLE
qshift issues

### ISSUE THREAD

**Issue by uranix** [oseledets/ttpy#26]
The `qshift` function (generate a shift matrix in QTT format) is broken at the moment. Steps to reproduce:
```
import tt
tt.qshift(5)
```
The failing code is at line tools.py:761
```
return Toeplitz(_vector.vector.from_list(x), kind='L')
```
since the list representation of tt-vector `x` is invalid.

**Comment by oseledets** [comment]
Fixed in https://github.com/oseledets/ttpy/commit/a3a0ad63351dfc340e50ca79ac2ff845f2c99201
