### ISSUE TITLE
test_ACA.py

### ISSUE THREAD

**Issue by OLGA1294** [oseledets/ttpy#27]
Здравствуйте! При тестирование файла test_ACA.py выявляется ошибка. Как решить данную проблему?
![default](https://cloud.githubusercontent.com/assets/23090496/19753320/d9501da2-9c2d-11e6-814c-16f2f3f3881a.PNG)
https://gist.github.com/OLGA1294/b15a9ca6282c511919d058c40340579a

**Comment by uranix** [comment]
Какую версию tt вы используете? В последней версии такого не наблюдаю.

**Comment by oseledets** [comment]
@OLGA1294 Надо взять ветку develop

**Comment by daskol** [comment]
Stale issue.
