### ISSUE TITLE
компиляция

### ISSUE THREAD

**Issue by OLGA1294** [oseledets/ttpy#28]
При вводе команды python setup.py install выводится следующая ошибка:
error: [Errno 2] No such file or directory: 'tt-fort/print/putstrmodule.F90'
Как решить данную проблему?

**Comment by uranix** [comment]
Похоже, что у вас не скачаны зависимости (tt-fort, rectcross, rect_maxvol). Если вы скачивали через git, то достаточно сделать
`git submodule update --init --recursive *`
Инструкция по установке есть в файле README
