### ISSUE TITLE
New pip version doesn't install

### ISSUE THREAD

**Issue by Bihaqo** [oseledets/ttpy#36]
```
ValueError: 'tt/cross/rectcross/rect_maxvol' is not a directory
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-FoqvEX/ttpy/
```

**Comment by uranix** [comment]
Please, provide more info: what was the exact command and what's your building environment?

**Comment by Bihaqo** [comment]
I can't reproduce the problem: ttpy just installed on two machines without an issue. Probably did something stupid previously.

Sorry for bothering.
