### ISSUE TITLE
`tt.matrix.full()` seems to produce wrong matrix

### ISSUE THREAD

**Issue by c-f-h** [oseledets/ttpy#70]
I cannot get the `full()` method of the `tt.matrix` class to give back the original matrix; instead it seems to be permuted somehow. Below is a simple example for a 1D Laplacian matrix with 2^6 degrees of freedom.

Am I misusing the method or is this a bug in the library?

```
import numpy as np
import tt

# 1D Laplacian matrix
A = np.diag(64*(2,)) - np.diag(63*(1,), 1) - np.diag(63*(1,), -1)
ATT = tt.matrix(A.reshape(12*(2,)))
A2 = ATT.full()

np.linalg.norm(A - A2)

>> 15.874507866387544
```

**Comment by ankineri** [comment]
Hope that helps (note the order, TT uses Fortran order):
```
A = np.diag(64*(2,)) - np.diag(63*(1,), 1) - np.diag(63*(1,), -1)
ATT = tt.matrix(A.reshape(12*(2,), order='F'))
A2 = ATT.full()

np.linalg.norm(A - A2)
>>> 3.0537713071361314e-14
```

**Comment by c-f-h** [comment]
Thanks, that's useful. I hadn't seen this documented anywhere, nor any simple usage examples.
