### ISSUE TITLE
matrix times vector = matrix 

### ISSUE THREAD

**Issue by vbatista73** [oseledets/ttpy#72]
The code  below shows that the multiplication of a tt.matrix and a tt.tensor gives the following incorrect output

xxyy= This is a 2-dimensional matrix 
r(0)=1, n(0)=2, m(0)=2 
r(1)=1, n(1)=2, m(1)=2 
r(2)=1 

xxyy.core= [0. 0. 0. 0.]

# test code starts here
from __future__ import print_function, absolute_import, division
import sys
sys.path.append('../')
import numpy as np
import math
import tt

x = [[0,1],[1,0]]
x = np.array(x,dtype=np.float)
xx=tt.matrix(x)
xx=tt.kron(xx,xx)

y=[1,0]
y=np.array(y,dtype=np.float)
yy=tt.tensor(y)
yy=tt.kron(yy,yy)

xxyy=xx*yy
print("xxyy=",xxyy)
print("xxyy.core=",(xxyy.tt).core)

**Comment by oseledets** [comment]
The supported interface for matrix-by-vector product in ttpy is tt.matvec(xx, yy). The product of tt.matrix and tt.vector should not actually work, seems like a bug that it does not return any error.
