### ISSUE TITLE
ksl with complex matrix

### ISSUE THREAD

**Issue by vbatista73** [oseledets/ttpy#73]
ksl with complex matrix does not give the correct output, as shown by the code below comparing to the propagation with exponential, obtained by scaling and squaring, that properly reproduces  Fig. 2 for the Heisenberg model with N=20, as reported by E. Rufeil Fiori, H.M. Pastawski Chem. Phys. Lett. (2006) 420: 35-41.
[myksl.txt](https://github.com/oseledets/ttpy/files/3278067/myksl.txt)

**Comment by qbit-** [comment]
Could you please format your test example as code with proper indentation? I can not reproduce it as it complains about missing Atau

**Comment by vbatista73** [comment]
Dear Atanu: Please, let me know if that works better. Victor.
`from __future__ import print_function, absolute_import, division
import sys
sys.path.append('../')
import numpy as np
import math
import tt
import tt.ksl
import matplotlib.pyplot as plt
def expA(A,eps):
    rmax=4
    N=10
    w0=A*(1.0/2**N)
    e=tt.eye(2,A.d)
    e=tt.matrix(e)
    tm=e
    k=N-1
    while k > 0:
        tm=e+tm*w0*(1.0/k)
        tm=tm.round(eps,rmax)
        k=k-1
    while k < N:
        tm=tm*tm
        tm=tm.round(eps,rmax)
        k=k+1
    return tm
def ham(N):
    x = np.array([[0,1],[1,0]])
    y = np.array([[0,complex(0,-1)],[complex(0,1),0]])
    z = np.array([[1,0],[0,-1]])
    tt_x=tt.matrix(x)
    tt_y=tt.matrix(y)
    tt_z=tt.matrix(z)
    eps  = 1e-14
    eps0 = 1.3/2
    epsn = 2.0/2
    v0   = 0.75/2
    vn   = 1.0/2
    tt_H=0*tt.eye(2,N)
    tmp=tt_H
    k=0
    while k < N:
        if k == 0:
            tmp=tt.matrix(eps0*z)
            tmp=tt.kron(tmp,tt.eye(2,N-1))
        else:
            tmp=tt.kron(tt.eye(2,k),tt.matrix(epsn*z))
            tmp=tt.kron(tmp,tt.eye(2,N-k-1))
        tt_H=tt_H+tmp
        tt_H=tt_H.round(eps)
        k=k+1
    tt_HNNx=0*tt.eye(2,N)
    tt_HNNy=tt_HNNx
    tt_HNNz=tt_HNNx
    k=0
    while k < N-1:
        if k == 0:
            tmpX=tt.kron(tt_x,tt_x)*v0
            tmpY=tt.kron(tt_y,tt_y)*v0
            tmpZ=tt.kron(tt_z,tt_z)*0
        else:
            tmp=tt.eye(2,k);
            tmpX=tt.kron(tmp,tt.kron(tt_x,tt_x)*vn)
            tmpY=tt.kron(tmp,tt.kron(tt_y,tt_y)*vn)
            tmpZ=tt.kron(tmp,tt.kron(tt_z,tt_z)*0)
        if k < N-2:
            tmpX=tt.kron(tmpX,tt.eye(2,N-2-k))
            tmpY=tt.kron(tmpY,tt.eye(2,N-2-k))
            tmpZ=tt.kron(tmpZ,tt.eye(2,N-2-k))
        tt_HNNx=tt_HNNx+tmpX
        tt_HNNy=tt_HNNy+tmpY
        tt_HNNz=tt_HNNz+tmpZ
        k=k+1
    tt_H=tt_H+tt_HNNx+tt_HNNy+tt_HNNz
    tt_H=tt_H.round(eps)
    return tt_H;
if __name__ == "__main__":
    N = 20
    su = np.array([1,0])
    sd = np.array([0,1])
    tau=0.1
    tfin=25
    nsteps=250
    eps=1e-14
    y0=tt.tensor(su, eps)
    for j in range(N-1):
        y0=tt.kron(y0,tt.tensor(sd, eps))
    A = ham(N)*complex(0.0,1.0)
    Atau=-A*tau
    eA= expA(Atau,eps)
    t= np.arange(0,tau*(nsteps),tau)
    p = np.empty_like(t)
    pr = np.empty_like(t)
    y=y0
    yr=y0
    for k in xrange(nsteps):
        if k > 0:
            y = tt.ksl.ksl(A, y, tau);
            yr = tt.matvec(eA,yr)
            y=y.round(eps,4)
            yr=yr.round(eps,4)
        p[k] = abs(tt.dot(y,y0))**2
        pr[k] = abs(tt.dot(yr,y0))**2
    plt.yscale('log')
    plt.plot(t,p,'b',label='ksl')
    plt.plot(t,pr,'-',label='exp')
    plt.legend()
    plt.show()
`

**Comment by vbatista73** [comment]
Dear Atanu:
Here's the code: 
[myksl copy.txt](https://github.com/oseledets/ttpy/files/3278052/myksl.copy.txt)

**Comment by oseledets** [comment]
I think I figured out what is the problem: after testing one matvec with exponent, and by ksl, the difference is the output of the second one is the complex conjugate of the first one.

**Comment by oseledets** [comment]
Now I got what is the problem. We need to use larger artificial rank for KSL.
