### ISSUE TITLE
Compilation error in `ort.f`

### ISSUE THREAD

**Issue by abrazhe** [oseledets/ttpy#80]
Running `python setup.py build` fails with multiple errors of the kind:
```
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/COMPLEX(8)).
tt/tt-fort/ort.f90:216:22:
```
with several different line numbers. Is there a simple fix for that? Could it be due to fortran compiler version mismatch or something like that?

Affects both master and develop branches.

**Comment by abrazhe** [comment]
More detailed error message:
```
error: Command "/usr/bin/gfortran -Wall -g -fno-second-underscore -fPIC -O3 -funroll-loops -I/home/brazhe/opt/anaconda3/envs/py38/lib/python3.8/site-packages/numpy/core/include -Ibuild/temp.linux-x86_64-3.8 -Ibuild/temp.linux-x86_64-3.8 -Ibuild/temp.linux-x86_64-3.8 -I/home/brazhe/opt/anaconda3/envs/py38/include/python3.8 -c -c tt/tt-fort/ort.f90 -o build/temp.linux-x86_64-3.8/tt/tt-fort/ort.o -Jbuild/temp.linux-x86_64-3.8 -Ibuild/temp.linux-x86_64-3.8" failed with exit status 1
```

**Comment by daskol** [comment]
The issue origin is that the compiler performs more strict argument list type checking in new [gfortran 10 release][1]. Unfortunately, this release affects a lot of open software. So, the common solution is to turn this error to warning as follows.
```bash
FFLAGS="-w -fallow-argument-mismatch" python setup.py install
```

[1]: https://gcc.gnu.org/gcc-10/changes.html#fortran

**Comment by abrazhe** [comment]
Thanks, this worked
