### ISSUE TITLE
How does tt.col work?

### ISSUE THREAD

**Issue by pratikac** [oseledets/ttpy#9]
Something like 
```
a = tt.tensor(np.array([[1,2],[3,4]]))
print tt.col(a, 0).full()
```
just gives ``[[1,2],[3,4]]`` again. Is it possible to have a function to pull out specific columns, i.e., the equivalent of ``A[:, 3, :, 4]`` in numpy? Also, it'd be nice to have an equivalent of ``np.transpose``.

**Comment by Bihaqo** [comment]
Imagine that you have a tensor and you store a vector in each cell. A tensor of vectors.
It seems like b = tt.col(a, k) is meant to extract a tensor with number, where for any index idx
b[idx] = a[idx][k].

There should be a tt.transpose for the tt.matrix. For tensors, however, shuffling the dimensions means completely destroying the tt structure and building it from scratch. It is a very expensive operation and it is not obvious how a user would want it to be implemented. You have to basic options:
b = tt.tensor(a.full().transpose(..))
Or running the cross approximation.

**Comment by pratikac** [comment]
I have a tensor, say ``A = tt.rand(10,5)``, and I would like to obtain ``A[:,:,:,i,j]`` where ``i,j`` can be on any of the other dimensions as well. I am looking at ``multifuncrs.py`` and maybe it has something?

I see, transposing the tensor is not very useful. I was hoping to use ``tt.col`` and transposing to implement to slicing above. Although, if the ranks and sizes are same in each dimension, transposing should be doable.

**Comment by Bihaqo** [comment]
Give me a few minutes, I'll write this function :)

> Although, if the ranks and sizes are same in each dimension, transposing should be doable (?).
I did not get the idea, why do you think it will make things easier?

**Comment by pratikac** [comment]
Wow, thanks a lot!

Perhaps I am missing something, but in the case where all sizes and ranks
are equal, you can just permutations the cores, right? E.g., if dim=2 swaps
with dim=3, A[:,i,j] should return A[:,j,i] which can be achieved by
swapping the cores and keeping tensor.ps the same.

On Thursday, February 25, 2016, Alexander Novikov <notifications@github.com>
wrote:

> Give me a few minutes, I'll write this function :)
>
> Although, if the ranks and sizes are same in each dimension, transposing
> should be doable (?).
> I did not get the idea, why do you think it will make things easier?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oseledets/ttpy/issues/9#issuecomment-188749814>.
>


-- 
P

**Comment by Bihaqo** [comment]
Done
https://github.com/oseledets/ttpy/pull/10

I made a separate pull request because my code slowed down the usual one element access. So a[1, 2, 3] used to be faster.

> Perhaps I am missing something, but in the case where all sizes and ranks
are equal, you can just permute the cores, right? E.g., if dim=2 swaps
with dim=3, A[:,i,j] should return A[:,j,i] which can be achieved by
swapping the cores and keeping tensor.ps the same.
Nope, because the matrix product is not commutative.

**Comment by pratikac** [comment]
>
> Nope, because the matrix product is not commutative.


Aah, yes.

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oseledets/ttpy/issues/9#issuecomment-188774935>.
>


-- 
P

**Comment by oseledets** [comment]
pratikac, actually transpose is possible approximately and is implemented in the MATLAB version of the Toolbox: https://github.com/oseledets/TT-Toolbox/blob/master/%40tt_tensor/permute.m

The idea is to do "inversions" for index shuffling. Yet not reimplemented in the Python version (although quite easy)
