### ISSUE TITLE
can not install on both py3 or py2....

### ISSUE THREAD

**Issue by Arsmart123** [oseledets/ttpy#92]
![image](https://user-images.githubusercontent.com/65449458/162673795-2c724b78-0c30-4380-a74e-77b57692a045.png)
![image](https://user-images.githubusercontent.com/65449458/162673833-d44a8ea5-1d6a-4489-afad-74d2110ded66.png)
Really can not install....I even tried py2, but also failed.....

**Comment by daskol** [comment]
OpenMP is missing. You can install it with Anaconda. Python 3 should be preferred.
